name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "self-hosted"
    steps:
    - uses: actions/checkout@v2
    - name: Building image
      run: docker build . -t vdeltex-web:latest --target prod
    - name: Stop container
      run: docker stop vdeltex-web && docker rm vdeltex-web || true
    - name: Start container
      run: docker run -p 127.0.0.1:30200:80 --name vdeltex-web -d vdeltex-web:latest
